### ISSUE TITLE
Sort order of performances

### ISSUE THREAD

**Issue by frauliessmann** [dwenzel/t3events#40]
At the moment the performances of an event are sort by their UID, but they have to be sort by the field "begin".

**Comment by dwenzel** [comment]
Do you mean the order in the field 'performances' of table tx_t3events_domain_model_event?

AFAIK it is not possible to configure this. They are displayed in the order of creation per default. There might be a way to achive this using the foreign_sortby [1] or foreign_default_sortby [2] option. 

You may also add a sorting field and set [...]['appearance']['useSortable'] => true (sort manually).

Please give it a try in a feature branch. 

(Consider this hint from TCA reference: "If you use the table only as an inline element, do not put the sortby field in the ctrl section, otherwise TYPO3 CMS will sort the entire table with every update. For example, if you have 10000 records, each with 4 inline elements, TYPO3 CMS will sort 40000 records even if only 4 must be sorted." )

[1] https://docs.typo3.org/typo3cms/TCAReference/Reference/Columns/Inline/Index.html#foreign-sortby
[2] https://docs.typo3.org/typo3cms/TCAReference/Reference/Columns/Inline/Index.html#foreign-default-sortby

**Comment by frau-liessmann** [comment]
Sorry, I meant the sorting order of performances in the frontend.

The plugin settings are:
- Performances > List/Detail
- Sort by: Date

I noticed the PerformanceController checks the field "performances.date", but it does not check the content of the field "performances.begin". So if there are several performances at the same day with different beginnings they will not get sorted by time.

**Comment by dwenzel** [comment]
done
