### ISSUE TITLE
SQL-Error when creating an event

### ISSUE THREAD

**Issue by Gene22** [dwenzel/t3events#70]
When saving an event I get the following error messages:

2: SQL error:' Incorrect integer value:'' for column' organizer' at row 1' (tx_t3events_domain_model_event: NEW59f6efced0331987700317)

2: SQL error:' Incorrect integer value:'' for column' sys_language_uid' at row 1' (tx_t3events_domain_model_performance: NEW59f6f00836052860313464)

The creation of venues and genres works.

Typo3 8.7.8

**Comment by dwenzel** [comment]
Hi @Gene22 
thanks for reporting this issue. 

Obviously the value **''** (empty string) is rejected. This is the default value which used to work for earlier TYPO3 versions. (since 4.5) 

Unfortunatly the handling of empty form values has been changed.
I will investigate it further within the next few days and provide a fix as soon as possible.
As a workaround you could make sure, there is at least one organizer and sys_language record. (even if you do not need them). These would then appear as default value. 
Another option is to hide the fields by adapting the TCA. 

cheers
Dirk

**Comment by KaiBroenstrup** [comment]
Hi @dwenzel ,
anything new here? I cant create an event for standard language (uid 0).
Thanks
Kai

**Comment by dwenzel** [comment]
Hi @KaiBroenstrup 
I can not reproduce this behaviour with the current version of t3events (0.40.1 and TYPO3 8.7.16) anymore
